# Generated by Django 3.2.8 on 2021-10-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_personalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numerodocumento', models.CharField(max_length=30, verbose_name='Número de documento')),
                ('nombrecompleto', models.CharField(max_length=30, verbose_name='Nombre completo')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('departamento', models.CharField(max_length=30, verbose_name='Departamento')),
                ('correocontacto', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefonocontacto', models.CharField(max_length=30, verbose_name='Teléfono ')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=30, verbose_name='NIT')),
                ('nombrecomercial', models.CharField(max_length=30, verbose_name='Nombre Comercial')),
                ('razonsocial', models.CharField(max_length=30, verbose_name='Razón Social')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('departamento', models.CharField(max_length=30, verbose_name='Departamento')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo de contacto')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoproducto', models.CharField(max_length=30, verbose_name='Código')),
                ('categoriaproducto', models.CharField(max_length=30, verbose_name='Categoría de producto')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripción')),
                ('genero', models.CharField(max_length=30, verbose_name='Género')),
                ('precio', models.IntegerField(default=0)),
                ('unidadesdisponibles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fechaemision', models.DateField(auto_now_add=True)),
                ('mediodepago', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('iva', models.IntegerField(default=16)),
                ('montoiva', models.IntegerField(default=0)),
                ('totalitem', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('totaliva', models.IntegerField(default=0)),
                ('totalmasimpuestos', models.IntegerField(default=0)),
                ('totaloperacion', models.IntegerField(default=0)),
                ('codigoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeproduct_products', to='authApp.products')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nit_home', to='authApp.home')),
                ('numerodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalid_clients', to='authApp.clients')),
            ],
        ),
    ]
